/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cbb;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author HIGG003
 */
public class ReportBet extends javax.swing.JFrame {

    /**
     * Creates new form ReportBet
     */
    public ReportBet() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mLChBx = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        schoolListforRB = new javax.swing.JComboBox<>();
        ouChBx = new javax.swing.JCheckBox();
        spreadChBx = new javax.swing.JCheckBox();
        yesCB = new javax.swing.JCheckBox();
        noCB = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        submitBetCB = new javax.swing.JButton();
        responseLa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mLChBx.setText("MoneyLine");

        jLabel1.setText("School:");

        schoolListforRB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ouChBx.setText("Over/Under");

        spreadChBx.setText("Spread");

        yesCB.setText("Yes");
        yesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesCBActionPerformed(evt);
            }
        });

        noCB.setText("No");

        jLabel2.setText("Did you win?");

        submitBetCB.setText("Submit");
        submitBetCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBetCBActionPerformed(evt);
            }
        });

        responseLa.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noCB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spreadChBx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mLChBx)
                                .addGap(18, 18, 18)
                                .addComponent(ouChBx))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(schoolListforRB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(yesCB)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitBetCB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(responseLa)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(schoolListforRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 213, Short.MAX_VALUE)
                        .addComponent(submitBetCB)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spreadChBx)
                            .addComponent(mLChBx)
                            .addComponent(ouChBx))
                        .addGap(2, 2, 2)
                        .addComponent(responseLa)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yesCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noCB)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>                        

    private void yesCBActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    final void init(){
        try {
            String blogUrl = "https://www.teamrankings.com/ncb/trends/ats_trends/";
            Document doc = Jsoup.connect(blogUrl).get();

            Element links = doc.select("body").get(0); // somehow grabs table
            Elements f = links.select("td");
            List<String> clist = f.eachText();
            ArrayList<String> schoolName = new ArrayList<>();
            for (int i = 0; i < clist.size(); i = i+5) {
            /////////    //gets school, ats record, cover%, mov, ATS+/-  all randomly
               schoolName.add(clist.get(i));
                
            }
            Collections.sort(schoolName);
            
            for(String e: schoolName){
                schoolListforRB.addItem(e);
            }
          
        } catch (IOException e) {
             System.out.println(e.toString());

        }
    }
    
    
    private void submitBetCBActionPerformed(java.awt.event.ActionEvent evt) {                                            
        //sql
        ResultSet rs = null;
        responseLa.setVisible(false);
        if(mLChBx.isSelected() && !spreadChBx.isSelected() && !ouChBx.isSelected()){
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            int uid=0;
            //get user id for sql table entry
            try (Connection con = DriverManager.getConnection("jdbc:mysql://db-betting.ci4zazu3dadi.us-east-1.rds.amazonaws.com/userTable", "admin", "Teacher1!") ) 
            {
                
                String query = "SELECT id_user FROM account WHERE username="+UserInfo.Login.un.trim()+";";
                PreparedStatement preparedStmt = con.prepareStatement(query);
                preparedStmt.execute();
                uid = rs.getInt(1);
                
            }
            
            try (Connection con = DriverManager.getConnection("jdbc:mysql://db-betting.ci4zazu3dadi.us-east-1.rds.amazonaws.com/userTable", "admin", "Teacher1!") ) 
            {
                //once you grab id , grab bet results from checkboxes and school
                String queryPut = "Insert INTO userGrid(id_user, school, WvS, LvS, ouW, ouL, mlW, mlL) VALUES (?,?,?,?);";
                PreparedStatement preparedStmtput = con.prepareStatement(queryPut);
                
                
                preparedStmtput.setInt(1, uid);
                
                if(yesCB.isSelected() && !noCB.isSelected()){
                    //if yes box is selected
                    preparedStmtput.setInt(7, uid);

                } else if (yesCB.isSelected() && !noCB.isSelected()){
                    //if no box is selected
                    
                } else {
                    //if false entry
                    responseLa.setText("Select possible Outcome");
                }
                preparedStmtput.execute();
            }
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
            
            
            
            
            this.setVisible(false);
        } else if(!mLChBx.isSelected() && spreadChBx.isSelected() && !ouChBx.isSelected()){
            
            
            
            
            
            this.setVisible(false);
        } else if (!mLChBx.isSelected() && !spreadChBx.isSelected() && ouChBx.isSelected()){
            
            
            
            
            
            
            this.setVisible(false);
        } else {
            responseLa.setVisible(true);
            responseLa.setText("Please select valid bet");
        }
        
        
        
        
        
        
        
        this.setVisible(false);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportBet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox mLChBx;
    private javax.swing.JCheckBox noCB;
    private javax.swing.JCheckBox ouChBx;
    private javax.swing.JLabel responseLa;
    private javax.swing.JComboBox<String> schoolListforRB;
    private javax.swing.JCheckBox spreadChBx;
    private javax.swing.JButton submitBetCB;
    private javax.swing.JCheckBox yesCB;
    // End of variables declaration                   
}

